/* ---------------- TOPICS ----------------
   Each item: ['Topic name', 'M'|'O'|'A', 'description', {w,depth,why,ex,q,week}]
   M = must, O = optional, A = advanced.
   w = interview weight: 3 asked in most interviews, 2 often, 1 occasionally.
   week = plan week (1-12) in which the topic is first taught; 0 = not in the plan.
   I() is a tiny helper that builds the item array (plain browser JS, no modules). */
function I(text,tag,desc,w,week,depth,why,ex,q){return [text,tag,desc,{w:w,depth:depth,why:why,ex:ex,q:q,week:week}];}

const TOPICS=[
{id:'sql',name:'SQL',emoji:'🗄️',
intro:'SQL is the most tested technical skill for Data Analysts. Almost every process has a live SQL round or an online SQL test, so it can be 40 to 50 percent of the technical interview.',
order:'Basics (SELECT, WHERE, GROUP BY) then JOINs and row counts, then CASE/NULL, CTEs, window functions, then the classic patterns; leave warehouse vocabulary and advanced items for last.',
items:[
 I('SELECT, WHERE, ORDER BY, LIMIT, DISTINCT','M','Filter and sort rows. AND/OR/NOT, IN, BETWEEN, LIKE.',3,1,
  'Write these without thinking, including AND/OR with brackets. You can skip rarely used operators.',
  'These are the building blocks of every query, so a weak answer here ends the interview early.',
  "SELECT DISTINCT city FROM customers WHERE age BETWEEN 25 AND 35 ORDER BY city LIMIT 10;",
  'Write a query to list the 10 most recent orders above 5000 rupees.'),
 I('Aggregations, GROUP BY, HAVING','M','COUNT/SUM/AVG/MIN/MAX. WHERE filters rows, HAVING filters groups.',3,1,
  'Group by one or more columns and filter groups with HAVING. Know that every non-aggregated column in SELECT must be in GROUP BY.',
  'Most business questions (sales by region, orders per customer) are a GROUP BY.',
  'SELECT region, SUM(amount) AS sales FROM orders GROUP BY region HAVING SUM(amount) > 100000;',
  'What is the difference between WHERE and HAVING?'),
 I('JOINs: INNER, LEFT, RIGHT, FULL, SELF','M','Know row counts when keys are duplicated.',3,1,
  'Explain each join with a small example and predict the row count. You can skip CROSS JOIN details, but know it multiplies rows.',
  'Data lives in many tables, and joins are the most common source of wrong numbers on the job.',
  'SELECT c.name, o.order_id FROM customers c LEFT JOIN orders o ON o.customer_id = c.id;',
  'Table A has 5 rows and table B has 3 rows, and the key repeats. How many rows does INNER JOIN return vs LEFT JOIN?'),
 I('Join row counts, duplicate keys and fan-out (double counting)','M','After a join, a one-to-many link repeats rows, so SUM and COUNT can be inflated.',3,1,
  'Be able to spot when a join multiplies rows and fix it by aggregating first (CTE) or using COUNT(DISTINCT). Know that a LEFT JOIN with a filter in WHERE turns into an INNER JOIN, so put the filter in ON.',
  'Interviewers use this to see if you check your numbers; a fan-out silently overstates revenue.',
  'orders (1 row) joined to order_items (3 rows) repeats the order amount 3 times, so SUM(o.amount) is 3x too big. Fix: SUM the items table, or aggregate items in a CTE first.',
  'You joined orders to order_items and revenue looks too high. What went wrong and how do you fix it?'),
 I('Joins on dirty keys (spaces, case, type mismatch, NULL keys)','M','Keys in real data are messy: trailing spaces, different case, text vs number, NULLs.',2,0,
  'Know the usual reasons a join drops or duplicates rows and how to clean the key in the ON clause or before. Remember NULL never equals NULL in a join.',
  'Real data never has perfectly clean IDs, and an analyst must notice when a join silently loses rows.',
  "ON TRIM(UPPER(a.code)) = TRIM(UPPER(b.code))   -- also check COUNT(*) before and after the join",
  'Your LEFT JOIN returns many NULLs even though you expected matches. What would you check?'),
 I('CASE WHEN and NULL handling','M','COALESCE, IS NULL, COUNT(*) vs COUNT(col).',3,1,
  'Use CASE WHEN for buckets and flags, COALESCE for defaults, and explain that COUNT(col) skips NULLs while COUNT(*) does not. Know NULL = NULL is not true.',
  'Business logic (age groups, status flags) is written with CASE, and NULL traps cause wrong counts.',
  "SELECT CASE WHEN amount >= 1000 THEN 'High' ELSE 'Low' END AS band, COUNT(*) FROM orders GROUP BY 1;",
  'What is the difference between COUNT(*), COUNT(column) and COUNT(DISTINCT column)?'),
 I('Type casting and integer division','M','CAST/CONVERT between types; dividing two integers can drop decimals in some databases.',2,0,
  'Know that 5/2 can return 2 in PostgreSQL and SQL Server (not in MySQL) and fix it with a decimal cast. You can skip the full list of type conversions.',
  'Percentages and rates are everywhere, and a silent integer division gives a wrong KPI.',
  'SELECT CAST(COUNT(DISTINCT buyer_id) AS DECIMAL) / COUNT(DISTINCT user_id) AS conversion FROM events;',
  'Why might your conversion rate query return 0 instead of 0.35?'),
 I('Subqueries (scalar, IN, correlated)','M','Often asked, then rewritten as a CTE.',2,1,
  'Write a subquery in WHERE and in FROM, and explain a correlated subquery. Prefer a CTE or join in your own work.',
  'Interviewers like to see if you can break a problem into steps.',
  'SELECT * FROM orders WHERE amount > (SELECT AVG(amount) FROM orders);',
  'Find employees who earn more than the average salary of their own department.'),
 I('CTEs (WITH)','M','Readable multi-step queries.',3,1,
  'Write a query with two or three chained CTEs and explain why it is more readable than nested subqueries.',
  'CTEs show clean thinking and are the standard way to write multi-step analysis queries.',
  'WITH m AS (SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY 1) SELECT * FROM m WHERE total > 5000;',
  'Rewrite this nested subquery as a CTE.'),
 I('Window functions: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, SUM() OVER','M','Top-N per group, running totals, MoM growth.',3,2,
  'Use PARTITION BY and ORDER BY, know the RANK vs DENSE_RANK vs ROW_NUMBER difference, and write a running total and a LAG for month-over-month change. Skip frame subtleties (ROWS vs RANGE).',
  'This is the main separator between basic and good SQL candidates in technical rounds.',
  'SELECT month, sales, sales - LAG(sales) OVER (ORDER BY month) AS mom_change FROM monthly_sales;',
  'Find the top 3 products by sales in each category.'),
 I('Date and string functions','M','DATE_TRUNC, EXTRACT, DATEDIFF, SUBSTRING, REPLACE, TRIM.',3,2,
  'Group by month or week, find days between two dates, and clean text with TRIM/LOWER/SUBSTRING. Function names differ by database, so say which one you use.',
  'Almost every real dataset has dates and messy text, and trends by month are the most common report.',
  "SELECT DATE_TRUNC('month', order_date) AS m, SUM(amount) FROM orders GROUP BY 1;",
  'How would you get monthly active users from a table of login events?'),
 I('Set operations: UNION, UNION ALL, INTERSECT, EXCEPT','M','UNION removes duplicates, UNION ALL does not.',2,2,
  'Explain the UNION vs UNION ALL difference and when you would use each. INTERSECT and EXCEPT are good to know.',
  'A very common short theory question and a handy way to combine similar tables.',
  'SELECT id FROM jan_users UNION ALL SELECT id FROM feb_users;',
  'What is the difference between UNION and UNION ALL, and which is faster?'),
 I('Duplicates, Nth highest, Top-N per group patterns','M','The classic trio.',3,2,
  'Find duplicates with GROUP BY and HAVING COUNT(*)>1, delete duplicates with ROW_NUMBER, and get the Nth highest with DENSE_RANK.',
  'These are the most repeated SQL interview questions across companies.',
  'SELECT salary FROM (SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) r FROM emp) t WHERE r = 2;',
  'Find the second highest salary without using LIMIT or TOP.'),
 I('EXISTS vs IN, NOT EXISTS patterns','M','Anti-join pattern: customers with no orders.',2,2,
  'Be able to find "customers with no orders" using LEFT JOIN ... IS NULL or NOT EXISTS. Know NOT IN breaks if the list contains NULL.',
  'Finding what is missing (no orders, no login) is a daily analyst question and a favourite test.',
  'SELECT c.id FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.customer_id IS NULL;',
  'List customers who have never placed an order.'),
 I('Order of execution','M','FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY, LIMIT.',2,1,
  'Recite the logical order and use it to explain why you cannot use a SELECT alias in WHERE.',
  'It shows you understand SQL rather than memorising syntax.',
  'FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY -> LIMIT',
  'Why does WHERE total > 100 fail when total is an alias defined in SELECT?'),
 I('Validating your query results','M','Sanity-check row counts, totals and duplicates before you share a number.',2,0,
  'Compare your total with a simple known figure, check row counts before and after joins, and look for NULLs and duplicates.',
  'A wrong number reaching a manager is the biggest risk for an analyst, so interviewers like candidates who self-check.',
  'SELECT COUNT(*), COUNT(DISTINCT order_id), SUM(amount) FROM final_table;  -- do these match the source?',
  'How do you make sure the output of a long SQL query is correct?'),
 I('NTILE, percent of total, gap detection','O','Window tricks: share of total, quartiles, finding missing days or IDs.',1,2,
  'Know the percent-of-total pattern (SUM() OVER ()). NTILE and gap detection are nice extras, so do not spend long on them.',
  'They appear in StrataScratch/DataLemur style questions but less in live entry-level interviews.',
  'SELECT region, SUM(amt) * 100.0 / SUM(SUM(amt)) OVER () AS pct FROM sales GROUP BY region;',
  'What percentage of total revenue does each region contribute?'),
 I('Pivoting with CASE WHEN','M','Conditional aggregation: rows to columns with SUM(CASE WHEN ...).',2,0,
  'Write SUM(CASE WHEN ...) to build a small pivot or to count by status in one query.',
  'Analysts constantly need a table with one column per month or status, and this is the portable way to do it.',
  "SELECT region, SUM(CASE WHEN status='Returned' THEN 1 ELSE 0 END) AS returns, COUNT(*) AS orders FROM o GROUP BY region;",
  'Show orders and returned orders per region in a single query.'),
 I('DB basics: PK, FK, normalization, fact vs dimension','M','Needed to talk about modeling.',2,4,
  'Define primary and foreign key, explain normalization in one example, and say fact tables hold numbers and events while dimensions hold descriptions.',
  'It shows you understand how the data you query is organised.',
  'fact_sales(order_id, product_id, date_id, amount) links to dim_product and dim_date.',
  'What is normalization and why do data warehouses often denormalize?'),
 I('OLTP vs OLAP','M','OLTP databases run day-to-day transactions; OLAP systems are built for analysis and reporting.',2,0,
  'Say OLTP = many small writes and reads (orders, payments), OLAP = large reads and aggregations over history. You can skip internals like cubes.',
  'Interviewers ask it to check you know where analysis data comes from and why you do not query the live app database.',
  'OLTP: insert one order. OLAP: total sales by month for 3 years.',
  'What is the difference between OLTP and OLAP systems?'),
 I('ETL vs ELT','M','ETL transforms data before loading; ELT loads raw data first and transforms inside the warehouse.',2,0,
  'Explain extract, transform, load, say Power Query is an ETL tool, and say modern cloud warehouses often use ELT. Skip tool details.',
  'Common concept question that shows you know how data reaches your dashboard.',
  'ETL: clean in Power Query, then load. ELT: load raw tables into BigQuery, then clean with SQL.',
  'What is ETL and how is it different from ELT?'),
 I('Data warehouse, data lake, data mart','O','A warehouse holds cleaned structured data, a lake holds raw data of any type, a mart is a small subject-focused warehouse.',1,0,
  'One-line definitions with an example are enough.',
  'Common vocabulary in JDs and in the first technical chat.',
  'Warehouse: sales tables for reporting. Lake: raw log files. Mart: marketing-only tables.',
  'What is the difference between a data warehouse and a data lake?'),
 I('SQL dialect differences','O','MySQL, PostgreSQL and SQL Server differ in LIMIT/TOP, date functions and string functions.',1,0,
  'Know the one dialect you practised and a few differences (LIMIT vs TOP vs FETCH FIRST). Interviewers accept it if you say so.',
  'Test platforms and companies use different databases and you should not be thrown by syntax.',
  'MySQL/PostgreSQL: LIMIT 5. SQL Server: SELECT TOP 5. Oracle: FETCH FIRST 5 ROWS ONLY.',
  'How would you get the top 5 rows in SQL Server?'),
 I('Views','O','Saved queries.',1,2,
  'Say a view is a saved query that acts like a table and helps reuse logic and hide complexity.',
  'Short concept question to check basic database knowledge.',
  'CREATE VIEW monthly_sales AS SELECT DATE_TRUNC(\'month\', order_date) m, SUM(amount) s FROM orders GROUP BY 1;',
  'What is a view and why would you use one?'),
 I('Indexes (what and why)','O','Speed up reads, slow writes.',1,2,
  'Explain an index as a lookup structure that speeds filters and joins but costs storage and write time. No need to know index types.',
  'Awareness shows you know why some queries are slow.',
  'CREATE INDEX idx_orders_cust ON orders(customer_id);',
  'What is an index and when would it not help?'),
 I('Temp tables, stored procedures (concept)','O','Awareness only.',1,0,
  'Know a temp table holds intermediate results and a stored procedure is saved reusable SQL code. Writing them is not expected.',
  'Appears in JDs for reporting teams and in some theory rounds.',
  'CREATE TEMP TABLE t AS SELECT ...;',
  'What is a stored procedure?'),
 I('Recursive CTEs','A','Hierarchies. Rare for entry-level.',1,2,
  'Just know it is a CTE that calls itself for tree data such as manager-employee. Skip writing one.',
  'Rare at entry level and usually only in harder online tests.',
  'WITH RECURSIVE t AS (SELECT id, boss FROM emp WHERE boss IS NULL UNION ALL SELECT e.id, e.boss FROM emp e JOIN t ON e.boss = t.id) SELECT * FROM t;',
  'How would you list all reports under a manager at any depth?'),
 I('Query optimization, EXPLAIN','A','High-level awareness is enough.',1,11,
  'Be able to say: select only needed columns, filter early, avoid functions on indexed columns, and read EXPLAIN at a high level.',
  'Asked occasionally to see if you can think about big tables.',
  'EXPLAIN SELECT * FROM orders WHERE customer_id = 5;',
  'A query is running slowly. What would you try first?'),
 I('Transactions, ACID, triggers, partitioning','A','Not needed for analysts at entry level.',1,0,
  'Know ACID by name only. These are developer and DBA topics.',
  'Sometimes asked in generic database rounds, not in analyst-specific ones.',
  'ACID = Atomicity, Consistency, Isolation, Durability.',
  'What does ACID stand for?')
]},

{id:'excel',name:'Excel',emoji:'📗',
intro:'Excel is used in aptitude tests, scenario rounds and in daily work at almost every company. Expect a short practical task or a few formula questions, roughly 15 to 25 percent of a typical process.',
order:'Lookups and conditional functions first, then pivot tables, then cleaning and charts, then dynamic arrays and the data model; macros last or never.',
items:[
 I('XLOOKUP, VLOOKUP, INDEX-MATCH','M','Know limits of VLOOKUP.',3,3,
  'Use XLOOKUP and VLOOKUP with exact match, and explain that VLOOKUP looks only to the right and breaks if columns move. Know INDEX-MATCH as the older flexible option.',
  'Joining two sheets is the most common Excel task, so this is asked in almost every Excel round.',
  '=XLOOKUP(A2, Products[ID], Products[Price], "Not found")',
  'What are the limitations of VLOOKUP and how does XLOOKUP fix them?'),
 I('SUMIFS, COUNTIFS, AVERAGEIFS','M','Conditional aggregation.',3,3,
  'Write them with two or more conditions, including date ranges and wildcards.',
  'They are the formula version of GROUP BY and are used in nearly every report.',
  '=SUMIFS(C:C, A:A, "North", B:B, ">="&DATE(2025,1,1))',
  'Sum sales for the North region in January using a formula.'),
 I('IF, IFS, AND, OR, IFERROR','M','Logic.',3,3,
  'Nest or combine logic for categories and flags, and wrap risky formulas in IFERROR. Prefer IFS or a lookup table over deep nesting.',
  'Basic logic tests quickly show if you can build business rules.',
  '=IF(AND(B2>=50, C2="Yes"), "Pass", "Fail")',
  'Create a column that labels customers High, Medium or Low from their spend.'),
 I('Text and date functions','M','LEFT, MID, TEXTJOIN, TEXT, EOMONTH, DATEDIF.',2,3,
  'Split and join text, extract month or year, and compute days between dates. Know that dates are stored as numbers.',
  'Cleaning IDs, names and dates is routine, and a typical practical includes it.',
  '=TEXT(A2,"mmm-yyyy")  and  =DATEDIF(A2,B2,"d")',
  'How would you extract the domain from an email address?'),
 I('Pivot tables and pivot charts','M','Grouping, slicers, calculated fields.',3,3,
  'Build a pivot with rows, columns, values, filters and slicers, group dates by month, and show values as percent of total. Remember to refresh when data changes.',
  'Pivots are the fastest summary tool and almost always part of an Excel test.',
  'Rows: Region. Columns: Month. Values: Sum of Sales (% of Column Total).',
  'Build a pivot to show monthly sales by category and explain what a slicer does.'),
 I('Conditional formatting and data validation','M','Dropdowns and highlights.',2,3,
  'Highlight duplicates or values above a threshold, and create a dropdown list with data validation.',
  'It shows attention to usability and data entry quality.',
  'Data > Data Validation > List: Yes,No,Maybe',
  'How do you highlight duplicate values in a column?'),
 I('Cleaning: remove duplicates, text-to-columns, TRIM','M','Always asked as a practical.',3,3,
  'Remove duplicates, fix spaces and case, split columns, convert text-numbers, and standardise dates. Say what you checked at each step.',
  'Real data is messy and the task shows whether you can prepare data for analysis.',
  '=TRIM(CLEAN(A2))  then  =VALUE(B2) for numbers stored as text',
  'You get a messy customer file. Walk me through how you would clean it.'),
 I('Dirty-key lookups: TRIM, text vs number, #N/A debugging','M','Lookups fail when IDs have spaces, different case or are stored as text in one sheet and numbers in the other.',2,3,
  'Know the usual causes of #N/A and how to fix them (TRIM the key, convert type, use exact match).',
  'It is the Excel twin of joins on dirty keys and a very common real-life problem.',
  '=XLOOKUP(TRIM(A2), Master[ID], Master[Name], "Check key")',
  'Your VLOOKUP returns #N/A for IDs that clearly exist. What would you check?'),
 I('Absolute vs relative references','M','$A$1.',2,3,
  'Explain $A$1, A$1 and $A1 and when the formula copy changes.',
  'A simple check of formula-building skill.',
  '=B2/$B$10  (fixed total in B10, copied down)',
  'Why does my percentage formula break when I copy it down?'),
 I('Statistical functions: MEDIAN, STDEV, PERCENTILE, CORREL, RANK','M','Quick descriptive statistics directly in Excel.',2,0,
  'Compute mean, median, standard deviation, percentile and correlation with formulas and read the result.',
  'Links statistics to the tool most employers use daily.',
  '=PERCENTILE.INC(B2:B200, 0.9)  and  =CORREL(B2:B200, C2:C200)',
  'How would you find the 90th percentile of delivery time in Excel?'),
 I('Charts and a basic dashboard','M','Pick the right chart.',2,3,
  'Choose bar, line, pie or scatter for the question, label axes, and combine a few charts with slicers on one sheet.',
  'Presenting results clearly is part of every analyst role.',
  'Trend over time = line. Compare categories = bar. Share of 3 parts = pie or stacked bar.',
  'Which chart would you use to show monthly sales trend and why?'),
 I('Dynamic arrays: FILTER, UNIQUE, SORT','O','Modern Excel.',2,3,
  'Know what FILTER, UNIQUE and SORT do and that they spill results into cells. Needs Excel 365 or 2021.',
  'Listed more and more in modern JDs and quick to demo.',
  '=SORT(UNIQUE(FILTER(A2:A100, B2:B100="North")))',
  'How would you get a list of unique customers from the North region?'),
 I('Named ranges, Tables','O','Cleaner formulas.',1,3,
  'Know Ctrl+T makes a Table with auto-expanding ranges and readable references.',
  'Makes formulas and pivots easier to maintain.',
  '=SUM(Sales[Amount])',
  'Why use an Excel Table instead of a normal range?'),
 I('SUMPRODUCT and array thinking','O','Multiply and add arrays in one formula without helper columns.',1,0,
  'A simple SUMPRODUCT weighted-average example is enough.',
  'Occasionally used for weighted averages and multi-condition sums.',
  '=SUMPRODUCT(B2:B10, C2:C10)/SUM(C2:C10)  (weighted average)',
  'How do you compute a weighted average in Excel?'),
 I('Power Pivot / Data Model','O','Bridge to Power BI.',1,3,
  'Know that it lets Excel handle relationships between tables and DAX measures, like a small Power BI.',
  'Shows the path from Excel to BI tools.',
  'Add two tables to the Data Model, link on CustomerID, then build one pivot on both.',
  'What is the Data Model in Excel?'),
 I('What-if, Goal Seek','O','Scenario analysis.',1,0,
  'Know Goal Seek finds the input needed for a target result.',
  'Used in finance and planning roles.',
  'Goal Seek: set profit cell to 50000 by changing price cell.',
  'How would you find the price needed to reach a profit target?'),
 I('VBA / macros, Office Scripts, LAMBDA','A','Not needed for entry-level.',1,3,
  'Know what a macro is, but do not learn VBA for entry-level interviews.',
  'Only senior or reporting-automation roles ask for it.',
  'Record a macro to apply the same formatting every month.',
  'Have you automated any repeated Excel task?')
]},

{id:'pbi',name:'Power Query & Power BI',emoji:'📊',
intro:'Power BI (or Tableau) is the main dashboard tool in most Indian Data Analyst job descriptions. Expect DAX and data model questions plus a walk-through of one dashboard you built, about 20 to 30 percent of the process.',
order:'Power Query cleaning, then star-schema model, then visuals and chart choice, then measures and CALCULATE, then time intelligence and dashboard design; advanced DAX last.',
items:[
 I('Power Query: connect, types, split, replace, fill','M','The ETL layer.',3,3,
  'Connect to Excel/CSV/SQL, set data types, split and replace columns, fill down, and remove errors. Explain that steps are recorded and repeat on refresh.',
  'Clean data in Power Query and the dashboard is trustworthy; it is the ETL part of the job.',
  'Transform: Split Column by delimiter, Replace Values, Fill Down, change Type to Date.',
  'How do you clean data in Power BI before building a report?'),
 I('Merge vs Append, Unpivot, Group By','M','Very common.',3,3,
  'Merge = join columns from another table, Append = stack rows, Unpivot = columns to rows (for months or survey questions).',
  'Used on almost every real dataset.',
  'Unpivot Jan, Feb, Mar columns into Month and Sales columns.',
  'What is the difference between Merge and Append queries?'),
 I('Data model: star schema, relationships','M','Fact and dimension tables, 1:many.',3,4,
  'Draw a star schema with one fact table and dimension tables and say why it is better than one flat table or a messy web of tables.',
  'Interviewers ask this to see if you can build models that give correct numbers.',
  'Sales (fact) -> Product, Customer, Date (dimensions) using 1:many relationships.',
  'What is a star schema and why do we use it?'),
 I('Cardinality and filter direction','M','1:many, many:many, single vs both direction filtering.',2,4,
  'Explain 1:many, why many-to-many is risky, and why single direction is the safe default.',
  'Wrong relationships give wrong totals without any error message.',
  'Product[ID] 1 -> * Sales[ProductID], filter flows from Product to Sales.',
  'What happens if two tables are connected many-to-many?'),
 I('Visuals, slicers, filters','M','Choose visuals by question.',2,4,
  'Use bar, line, card, table, matrix, map and slicer, and know page vs visual vs report filters.',
  'Everyday dashboard work.',
  'Card = total sales. Line = trend. Matrix = region by month.',
  'What is the difference between a slicer and a filter?'),
 I('Choosing the right chart and avoiding misleading visuals','M','Match chart to question; avoid 3D, truncated axes and too many colours or slices.',3,4,
  'Pick a chart for trend, comparison, share, distribution and relationship, and name two ways charts mislead.',
  'Shows data literacy and is asked in many practical and manager rounds.',
  'A bar chart with the axis starting at 90 instead of 0 exaggerates small differences.',
  'When would you not use a pie chart?'),
 I('Measures vs calculated columns','M','Frequent question.',3,4,
  'Say a calculated column is computed per row at refresh and stored, while a measure is calculated on the fly using the current filters. Use measures for totals and ratios.',
  'It tests whether you understand how DAX evaluates.',
  'Margin % = DIVIDE(SUM(Sales[Profit]), SUM(Sales[Revenue]))  -- a measure, not a column.',
  'When would you use a calculated column rather than a measure?'),
 I('DAX basics: SUM, COUNTROWS, DISTINCTCOUNT, DIVIDE, IF, SWITCH','M','Net Sales, Unique Customers.',3,4,
  'Write simple measures from memory and use DIVIDE to avoid divide-by-zero.',
  'Live DAX questions are common in Power BI interviews.',
  'Unique Customers = DISTINCTCOUNT(Sales[CustomerID])',
  'Write a measure for average order value.'),
 I('CALCULATE, filter context vs row context','M','The heart of DAX.',3,4,
  'Explain filter context in plain words, and use CALCULATE to change it with a condition. Skip context transition details.',
  'The classic DAX question that separates beginners from capable users.',
  'North Sales = CALCULATE(SUM(Sales[Amount]), Sales[Region] = "North")',
  'What does CALCULATE do?'),
 I('ALL, ALLEXCEPT, FILTER for percent of total','M','Remove filters to compare a part with the total.',2,4,
  'Write a percent-of-total measure with DIVIDE and CALCULATE(ALL(...)).',
  'Percent of total and ranking are the next DAX question after CALCULATE.',
  '% of Total = DIVIDE([Sales], CALCULATE([Sales], ALL(Product)))',
  'How do you show each category as a percentage of total sales?'),
 I('Calendar table + time intelligence','M','YTD, MoM, YoY.',3,5,
  'Create or mark a Date table and write YTD and same-period-last-year measures.',
  'Trend and growth comparisons are in nearly every business dashboard.',
  "Sales YTD = TOTALYTD([Sales], 'Date'[Date])   YoY = DIVIDE([Sales] - [Sales LY], [Sales LY])",
  'Why do we need a separate date table?'),
 I('Dashboard design principles','M','KPI row, minimal visuals, consistent colors.',3,5,
  'Put the key KPIs on top, limit visuals per page, keep colours and fonts consistent, and design for the audience question.',
  'Good design makes the dashboard usable by managers.',
  'Layout: KPI cards on top, one trend, one breakdown, filters on the left.',
  'How do you decide what goes on a dashboard?'),
 I('Dashboard critique: spot problems in a bad dashboard','M','Be able to review a dashboard and say what is unclear or misleading.',2,0,
  'List problems such as too many visuals, unclear titles, wrong chart, no context or target, and inconsistent filters, then say how to fix each.',
  'Some interviews show a sample dashboard and ask what you would improve.',
  'Fix: add title with the question, show a target line, remove 3D and unused slicers.',
  'Here is a dashboard. What would you change?'),
 I('Publish and share (Service) concept','O','Workspace, refresh, gateway concept.',2,4,
  'Know that you publish to the Service, schedule refresh, and a gateway connects to on-premises data. If you cannot publish, explain the concept and show screenshots.',
  'Shows you understand the end-to-end flow; many companies block the Service on personal accounts.',
  'Desktop -> Publish -> Workspace -> Scheduled refresh -> Share app.',
  'How does a report get from Power BI Desktop to business users?'),
 I('Drill-through, bookmarks, tooltips','O','Interactivity.',2,5,
  'Know what drill-down, drill-through and a bookmark each do, with one example.',
  'Makes dashboards interactive and is often mentioned when you walk through a project.',
  'Right-click a region -> Drill through to a Region detail page.',
  'What is the difference between drill-down and drill-through?'),
 I('Conditional formatting, parameters','O','Polish.',1,5,
  'Use colours or icons to flag values above or below target.',
  'Small touches that make dashboards readable.',
  'Conditional format: red if Margin % < target.',
  'How would you highlight underperforming regions?'),
 I('Row-level security (RLS)','O','Often asked as a concept.',2,0,
  'Explain RLS as filtering the rows a user can see based on a role, with a one-line example.',
  'Common concept question in company dashboards with regional managers.',
  'Role: Region = USERPRINCIPALNAME() match so each manager only sees their region.',
  'How can each sales manager see only their own region in one report?'),
 I('Import vs DirectQuery','O','Trade-offs.',2,0,
  'Import = fast, data copied and refreshed on schedule. DirectQuery = live but slower and with feature limits.',
  'Shows you can choose a connection mode for data size and freshness.',
  'Import for 1 million rows and daily refresh; DirectQuery for near real-time on a large warehouse.',
  'When would you choose DirectQuery over Import?'),
 I('RANKX, TOPN and top-N measures','O','Rank products or customers and show the top few.',1,0,
  'Know that these exist and write one top-N example.',
  'Top-N questions are common in dashboards and sometimes in DAX rounds.',
  'Rank = RANKX(ALL(Product[Name]), [Sales])',
  'How do you show the top 5 products by sales?'),
 I('DAX variables, SUMX/iterators','A','Nice to know.',1,0,
  'Know VAR makes DAX easier to read and SUMX loops row by row. Not required at entry level.',
  'Occasionally used to test depth beyond basics.',
  'Revenue = SUMX(Sales, Sales[Qty] * Sales[Price])',
  'When would you use SUMX instead of SUM?'),
 I('Performance Analyzer, incremental refresh, calc groups','A','Not needed at entry level.',1,0,
  'Awareness that big models need tuning is enough.',
  'Matters for senior BI developer roles.',
  'Use Performance Analyzer to find the slowest visual.',
  'A report is slow. Where would you look first?')
]},

{id:'py',name:'Python (pandas)',emoji:'🐍',
intro:'Python is listed in many Data Analyst job descriptions as required or preferred, but entry-level rounds focus on pandas for cleaning and aggregating, not machine learning. Expect a small coding or take-home task, about 10 to 20 percent of the process when the JD mentions it.',
order:'Basic Python structures, then read and inspect data with pandas, then selecting and cleaning, then groupby and merge, then charts; automation and extras last.',
items:[
 I('Data types and structures: list, tuple, set, dict','M','Mutable vs immutable.',2,6,
  'Know what each is for, which are mutable, and how to loop through a dictionary.',
  'Basic fluency is checked before pandas questions.',
  "counts = {'a': 3, 'b': 5}; for k, v in counts.items(): print(k, v)",
  'What is the difference between a list and a tuple?'),
 I('Control flow, functions, comprehension, lambda','M','Basics.',2,6,
  'Write loops, conditions, a small function and a list comprehension.',
  'Used in cleaning helper functions and simple screening questions.',
  'squares = [x*x for x in range(5) if x % 2 == 0]',
  'Write a function that returns the count of even numbers in a list.'),
 I('pandas Series/DataFrame, read_csv/read_excel','M','Load data.',3,6,
  'Load a CSV or Excel file and explain the difference between a Series and a DataFrame.',
  'Every analysis starts with loading data.',
  "df = pd.read_csv('sales.csv')",
  'What is a DataFrame?'),
 I('Inspecting data: head, info, describe, shape, value_counts','M','First look at any new dataset.',3,6,
  'Run the standard first-look commands and say what each reveals (types, nulls, ranges, categories).',
  'Interviewers watch if you explore data before analysing it.',
  "df.info(); df.describe(); df['city'].value_counts()",
  'You get a new dataset. What are your first five commands?'),
 I('Selecting and filtering: loc, iloc, boolean masks','M','Frequent.',3,6,
  'Select rows and columns by label and position, and filter with conditions combined using & and | with brackets.',
  'Filtering is the Python version of WHERE.',
  "df.loc[(df['sales'] > 1000) & (df['region'] == 'North'), ['order_id','sales']]",
  'What is the difference between loc and iloc?'),
 I('Cleaning: nulls, duplicates, dtypes, str methods, datetime','M','Day-to-day work.',3,6,
  'Find and handle missing values, drop duplicates, fix types, clean text with .str, and parse dates with to_datetime.',
  'Cleaning is most of the real job and a typical take-home focus.',
  "df['date'] = pd.to_datetime(df['date']); df = df.drop_duplicates(); df['city'] = df['city'].str.strip().str.title()",
  'How do you handle missing values in a DataFrame?'),
 I('groupby, agg, pivot_table','M','Aggregation.',3,6,
  'Group, aggregate with several functions, sort and take the top N. Say how it maps to SQL GROUP BY.',
  'The most common pandas analysis step.',
  "df.groupby('city')['sales'].sum().sort_values(ascending=False).head(5)",
  'Find the top 5 cities by total sales using pandas.'),
 I('merge, join, concat','M','Combine tables.',3,6,
  'Use merge with how=left/inner on a key and check row counts after, as with SQL joins.',
  'Real analysis combines several tables, and wrong merges give wrong numbers.',
  "orders.merge(customers, on='customer_id', how='left')",
  'What is the difference between merge and concat?'),
 I('Dates and time series basics: dt accessor, resample','O','Extract month or weekday and aggregate by period.',2,0,
  'Create month and weekday columns and resample to monthly totals.',
  'Trend-by-month analysis is very common.',
  "df.set_index('date')['sales'].resample('M').sum()",
  'How would you get monthly sales from a daily DataFrame?'),
 I('Outliers: z-score and IQR','M','A known interview task.',2,6,
  'Explain both methods and write a short function to flag outliers. Say you check why an outlier exists before removing it.',
  'A frequent short coding and statistics question.',
  "q1, q3 = s.quantile([.25, .75]); iqr = q3 - q1; mask = (s < q1 - 1.5*iqr) | (s > q3 + 1.5*iqr)",
  'How do you detect outliers in a column?'),
 I('apply / map vs vectorization','O','Performance awareness.',1,6,
  'Know vectorised column operations are faster than row-by-row apply, and use apply only when needed.',
  'Shows habits that scale to larger data.',
  "df['profit'] = df['rev'] - df['cost']   # better than df.apply(lambda r: ..., axis=1)",
  'Why is vectorization faster than apply?'),
 I('matplotlib / seaborn','M','Basic charts.',2,6,
  'Make a bar, line, histogram, box plot and scatter, with a title and labels.',
  'EDA and presenting results need quick charts.',
  "sns.boxplot(data=df, x='region', y='sales')",
  'Which plot shows the distribution and outliers of a numeric column?'),
 I('Jupyter notebooks','M','Working environment.',1,6,
  'Run cells, mix code and notes, and structure a notebook as a story.',
  'Take-home tasks are usually delivered as notebooks.',
  'Notebook: question -> load -> clean -> analyse -> chart -> conclusion.',
  'How do you present your analysis in a notebook?'),
 I('Reshaping: melt, pivot, stack','O','Wide to long and long to wide.',1,0,
  'Know melt turns columns into rows, useful for survey data.',
  'Common step when preparing data for charts or merges.',
  "pd.melt(df, id_vars='id', var_name='question', value_name='score')",
  'How do you convert month columns into rows?'),
 I('numpy, plotly, regex','O','Helpful.',1,6,
  'Know numpy arrays and basic regex patterns exist; practise one regex like extracting digits.',
  'Nice extras in JDs.',
  "df['phone'].str.extract(r'(\\d{10})')",
  'How would you extract numbers from a text column?'),
 I('APIs (requests), openpyxl automation, sqlite3/SQLAlchemy','O','Automation.',1,0,
  'A one-line idea of each is enough; mention if you built a small automation.',
  'Shows initiative, mostly in smaller companies.',
  "requests.get(url).json()",
  'Have you automated a report with Python?'),
 I('scikit-learn, OOP, forecasting, Streamlit','A','Not required.',1,6,
  'Know it exists but do not prepare it for entry-level DA interviews.',
  'Asked only for data science leaning roles.',
  'LinearRegression().fit(X, y)',
  'Have you built any prediction model?')
]},

{id:'stats',name:'Statistics',emoji:'📐',
intro:'Statistics for a Data Analyst is mostly descriptive stats plus clear thinking about samples, correlation and A/B tests. It is about 10 to 20 percent of the interview and must be explained in plain words, not formulas.',
order:'Mean, median and spread first, then distributions and sampling, then correlation, then hypothesis testing and A/B testing; regression and Bayes last.',
items:[
 I('Mean, median, mode, variance, std dev','M','Know when mean misleads.',3,7,
  'Explain each in one line and say median is better with skewed data such as salary or order value.',
  'The base of every summary and a warm-up question in most interviews.',
  'Salaries 30, 32, 35, 36, 400 -> mean 106.6 is misleading, median 35.',
  'When would you use median instead of mean?'),
 I('Percentiles, IQR, outliers','M','Box plot logic.',2,7,
  'IQR = Q3 minus Q1, and a common outlier rule is beyond 1.5 x IQR. Read a box plot.',
  'Links stats to data cleaning and charts.',
  'Q1=10, Q3=20, IQR=10, upper fence = 20 + 15 = 35.',
  'How do you read a box plot?'),
 I('Descriptive vs inferential statistics','M','Describing the data you have vs drawing conclusions about a larger population.',2,0,
  'Give one example of each, such as average sales (descriptive) vs estimating population satisfaction from a sample (inferential).',
  'A favourite fresher definition question.',
  'Average CSAT of 500 respondents = descriptive. Saying all customers are ~4.2 +/- 0.1 = inferential.',
  'What is the difference between descriptive and inferential statistics?'),
 I('Normal distribution, 68-95-99.7, skew','M','Basics.',2,7,
  'Describe the bell curve, the 68-95-99.7 rule and what left or right skew means for mean vs median.',
  'Underlies z-scores, outliers and testing.',
  'Right skew: long tail to the right, mean > median.',
  'What does a right-skewed distribution look like and what does it do to the mean?'),
 I('Population vs sample, sampling methods, bias','M','Survey relevant.',2,7,
  'Know random, stratified and cluster sampling and give examples of bias such as non-response and selection.',
  'Every dataset is a sample, so bias decides whether conclusions can be trusted.',
  'Online-only survey misses people without internet (selection bias).',
  'How could a survey sample be biased?'),
 I('Central Limit Theorem (idea)','M','Why sample means are normal.',2,7,
  'Say: averages of large random samples look normal even if the data itself is not, which is why confidence intervals and tests work. No proof needed.',
  'Common concept check for fresher stats.',
  'Daily order values are skewed, but average of 100 orders over many samples is close to normal.',
  'Explain the Central Limit Theorem in simple words.'),
 I('Correlation vs causation','M','Always asked.',3,7,
  'Say two things moving together does not prove one causes the other, and give an example with a hidden third factor.',
  'Stops analysts making wrong business claims.',
  'Ice cream sales and drowning rise together because of summer.',
  'Sales and ad spend are correlated. Can you say ads cause sales?'),
 I('Correlation coefficient and covariance','M','r ranges from -1 to 1; covariance shows direction but not strength.',2,0,
  'Say r near 1 is strong positive, near 0 is no linear relationship, and covariance depends on units while r does not.',
  'Appears in fresher question lists next to correlation vs causation.',
  'CORREL(price, demand) = -0.7 means strong negative linear relation.',
  'What is the difference between correlation and covariance?'),
 I('Hypothesis testing, p-value, confidence interval','M','"p = 0.04 so what?"',3,7,
  'State the null and alternative, say a small p-value means the result would be unlikely if the null were true, and a 95 percent interval is a plausible range. Do not say p is the chance the null is true.',
  'Used to judge whether a difference is real or noise.',
  'p = 0.04 at 5 percent level: reject the null, but also check the effect size.',
  'A test gives p = 0.04. How do you explain that to a manager?'),
 I('Type I and Type II errors','M','False positive vs false negative.',2,7,
  'Type I = flagging an effect that is not there, Type II = missing a real effect. Give a business example.',
  'Tests careful interpretation.',
  'Type I: launching a feature that does nothing. Type II: dropping a feature that works.',
  'What are Type I and Type II errors?'),
 I('A/B testing design','M','Metric, guardrails, sample size, duration.',3,7,
  'Pick a primary metric, set guardrail metrics, randomise users, run long enough for full weekly cycles, and avoid peeking early. Sample size calculation can stay conceptual.',
  'Product and marketing analysts run and read experiments constantly.',
  'Test new checkout button: metric conversion, guardrail refund rate, 2 weeks.',
  'How would you set up an A/B test for a new landing page?'),
 I('t-test, chi-square (concept)','O','When to use which.',2,7,
  't-test compares averages of two groups, chi-square checks relation between two categories. Know when to use each; do not memorise formulas.',
  'Often asked in one line, especially for survey and A/B roles.',
  'Average spend A vs B = t-test. Gender vs product preference = chi-square.',
  'Which test would you use to compare conversion between two groups?'),
 I('Simple regression idea, R-squared','O','Concept.',2,0,
  'Explain a line that predicts one variable from another, and R-squared as the share of variation explained.',
  'Occasionally asked as a concept for forecasting or driver analysis.',
  'R-squared 0.6: 60 percent of variation in sales is explained by the model.',
  'What does R-squared tell you?'),
 I('Bayes theorem','O','Occasionally asked.',1,0,
  'Know the idea of updating probability with new evidence and one worked example.',
  'Shows probability thinking in a few interviews.',
  'P(A|B) = P(B|A) * P(A) / P(B)',
  'A test is 90 percent accurate and 1 percent of people have the condition. Is a positive test conclusive?'),
 I('Margin of error and sample size','O','More respondents means a smaller margin of error; for a proportion it is about 1/sqrt(n) at 95 percent.',1,7,
  'Know roughly that 400 respondents gives about +/-5 percent and that it shrinks slowly.',
  'Important for survey and market research roles.',
  'n = 1000 -> margin of error about +/-3 percent.',
  'Why does a survey with 1000 people not give exact results?'),
 I('Simpson\'s paradox, survivorship bias, base rate','O','Classic traps that reverse or distort a conclusion.',2,0,
  'Give one simple example of each and say you always check segments.',
  'Used as tricky "what is wrong with this analysis" questions.',
  'Overall conversion drops, but it rises in every segment because the mix of users changed.',
  'Overall conversion went down but every segment improved. How is that possible?'),
 I('Advanced probability, ML metrics, time series','A','Not needed.',1,0,
  'Skip these for entry-level DA interviews.',
  'Appear for data scientist roles.',
  'Precision, recall, ARIMA.',
  'What is the difference between precision and recall?')
]},

{id:'biz',name:'Business & Analytics Thinking',emoji:'🧠',
intro:'This is how interviewers judge whether you can turn data into decisions: metric definitions, case questions, cleaning method, storytelling and aptitude. It decides most manager rounds, and online tests often include aptitude and data interpretation.',
order:'Metrics and KPIs first, then the data cleaning workflow and EDA, then funnel/cohort/RFM, then root-cause cases and storytelling, then aptitude and take-home practice.',
items:[
 I('KPIs and metrics: conversion, churn, retention, AOV, CAC, LTV, ROI','M','Define each in one line.',3,7,
  'Define each in one sentence with the formula and know which business question it answers.',
  'Every dashboard and case revolves around metrics.',
  'Conversion rate = orders / visitors. AOV = revenue / orders. Churn = customers lost / customers at start.',
  'How do you calculate customer churn rate?'),
 I('KPI vs metric, dimension vs measure, leading vs lagging','M','A KPI is a metric tied to a goal; dimensions slice measures; leading metrics predict, lagging ones report.',2,0,
  'Explain with one example each and say good metrics are clear, comparable and actionable.',
  'Shows you can define and choose metrics, not just compute them.',
  'Metric: page views. KPI: conversion rate vs target. Dimension: region. Measure: revenue.',
  'What is the difference between a metric and a KPI?'),
 I('Clarifying the business question','M','Before touching data, ask what decision it supports, who uses it and how success is measured.',3,0,
  'Ask 3 to 5 clarifying questions: goal, time period, definition, audience, existing data.',
  'Vague requests are normal, and good analysts clarify first.',
  'Request: "show sales". Ask: by what period, which region, vs what target, who is the reader?',
  'A manager asks for a sales report. What do you ask before you start?'),
 I('Funnel analysis','M','Where do users drop?',2,7,
  'Compute step conversion and overall conversion and identify the biggest drop.',
  'Common for e-commerce, marketing and product roles.',
  'Visit 1000 -> Cart 300 -> Pay 90: step conversion 30% and 30%, overall 9%.',
  'Where would you start if checkout conversion is low?'),
 I('Cohort and retention analysis','M','Group by signup period.',2,7,
  'Group users by signup month and track the share still active each month later.',
  'Shows whether the product keeps customers, beyond one-time totals.',
  'Jan cohort: 100 users, month 1 retained 40, month 2 retained 30.',
  'How would you compute 30-day retention in SQL?'),
 I('RFM segmentation','M','Recency, frequency, monetary.',2,8,
  'Score customers on Recency, Frequency and Monetary value and name segments such as champions and at risk.',
  'A classic e-commerce and marketing analysis, often in projects.',
  'Recent, frequent, high-spend = champion; not seen in 6 months = at risk.',
  'How would you segment customers for a marketing campaign?'),
 I('Root-cause framework for a metric drop','M','Data, then internal, then external, then segment.',3,7,
  'Check data and tracking first, then split by segment, channel and time, then internal changes and external events, and end with recommendations.',
  'The most common business case in manager rounds.',
  'Sales -25%: 1) data issue? 2) which region/product dropped? 3) price, stock or campaign change? 4) seasonality or competitor?',
  'Sales dropped 25 percent last month. What do you do?'),
 I('EDA process and data quality checks','M','Nulls, duplicates, ranges, logic.',3,3,
  'Check shape, types, nulls, duplicates, ranges and logic (e.g. end date before start date), then look at distributions and relationships.',
  'It shows you do not trust data blindly.',
  'Checks: nulls %, duplicate IDs, age between 0 and 100, delivered date >= order date.',
  'What checks do you do when you first receive a dataset?'),
 I('Data cleaning workflow and documenting assumptions','M','Profile, decide rules, fix, verify, and write down what you changed.',3,3,
  'Describe a repeatable method: profile the data, list issues, choose a fix for each, apply it, compare before and after, and keep a change log.',
  'Interviewers ask for your cleaning approach in most take-home and project discussions.',
  'Log: 120 duplicate order IDs removed; 35 blank cities set to Unknown; dates converted to ISO format.',
  'Walk me through how you clean a dataset from start to finish.'),
 I('Handling missing values: drop, fill, or flag','M','Choose by how much is missing and why it is missing.',3,3,
  'Know options: drop rows, fill with median or mode, forward fill for time data, or flag as Unknown. Say you check the percentage and reason before deciding.',
  'A standard fresher question with a judgement answer.',
  'Age missing in 2 percent of rows: fill with median. Income missing in 60 percent: do not fill, report it.',
  'How do you handle missing values?'),
 I('Storytelling and presenting to non-technical people','M','Insight, so-what, action.',3,5,
  'State the finding first, then the evidence, then the recommended action, in plain words and with one clear chart.',
  'Analysis only has value if people act on it.',
  'Headline: "Repeat orders fell 12 percent after delivery times went up. Recommend fixing the Pune warehouse."',
  'Explain your last analysis to someone with no data background.'),
 I('Validating numbers before sharing','M','Reconcile with a known total, sanity check ranges, and ask whether the result is plausible.',2,0,
  'Cross-check totals with a trusted source and check that growth rates and ratios look realistic.',
  'Builds trust; one wrong number can end a stakeholder relationship.',
  'Dashboard total revenue should equal the finance report within a small gap.',
  'How do you make sure your report numbers are right?'),
 I('Aptitude and data interpretation (tables, charts, percentages)','M','Online tests usually include it.',3,10,
  'Read a table or chart quickly and compute percentages, ratios, averages and growth without a calculator trap. Practise timed.',
  'Many Indian companies use aptitude as the first filter.',
  'Sales 80 -> 100 is +25 percent, not 20.',
  'Revenue rose from 80 to 100. What is the percentage increase?'),
 I('Percent change, percentage points, weighted average, CAGR','M','Core arithmetic that analysts get wrong under pressure.',3,0,
  'Know that 10% to 12% is +2 percentage points or +20% relative, how to compute a weighted average, and CAGR = (end/start)^(1/years) - 1.',
  'Aptitude and business cases both use it.',
  'CAGR from 100 to 144 over 2 years = (1.44)^(0.5) - 1 = 20%.',
  'Conversion went from 5% to 6%. How much did it improve?'),
 I('Case or take-home structure','M','Restate the problem, state assumptions, analyse, give 3 findings and recommendations.',2,10,
  'Use a simple structure: question, data and assumptions, method, findings, recommendation, next steps. Keep slides to about five.',
  'Take-homes and live cases are judged as much on structure as on the answer.',
  'Slide 1 summary, 2 method, 3 to 4 findings, 5 recommendations.',
  'How would you structure a 5-slide presentation of a take-home analysis?'),
 I('Choosing Excel vs SQL vs Python vs BI','M','Pick the tool by data size, repeatability and audience.',2,0,
  'Say Excel for small ad hoc work, SQL to pull and aggregate from databases, Python for heavy cleaning or automation, BI for shared dashboards.',
  'Interviewers use it to check you know the toolset.',
  '10 million rows: SQL first, then maybe Power BI. 500 rows one-off: Excel.',
  'When would you use SQL instead of Excel?'),
 I('Product metrics: DAU/MAU, stickiness, ARPU','O','Active users, how often they return and revenue per user.',1,0,
  'Define each and say DAU/MAU is a stickiness ratio.',
  'Appear in product analyst and app company interviews.',
  'DAU/MAU = 0.25 means the average user is active about 7 days a month.',
  'How would you measure whether users like a new app feature?'),
 I('Structured vs unstructured data; primary vs secondary data','O','Tables vs text, images and logs; collected by you vs already collected by others.',1,0,
  'One-line definitions with an example are enough.',
  'Appears on fresher definition lists.',
  'Structured: sales table. Unstructured: customer comments. Primary: your own survey.',
  'What is the difference between structured and unstructured data?'),
 I('Data privacy basics: PII and anonymisation','O','Do not share names, phone numbers or IDs unnecessarily; mask or aggregate.',1,0,
  'Know what PII is and that you share aggregated or masked data. India has the DPDP Act 2023, awareness is enough.',
  'Companies, especially in finance and research, care about safe handling.',
  'Share city-level totals instead of customer lists with phone numbers.',
  'How would you handle a dataset with customer phone numbers?'),
 I('Unit economics, segmentation','O','Deeper business sense.',1,0,
  'Know contribution per order or customer and how segments differ in profit.',
  'Used in business-heavy roles.',
  'Profit per order = revenue - cost of goods - delivery - discount.',
  'Are we making money on a typical order?'),
 I('Forecasting basics','O','Moving average, seasonality.',1,7,
  'Know a moving average, trend and seasonality at a high level.',
  'Occasionally asked in demand and finance roles.',
  '3-month moving average smooths monthly noise.',
  'How would you do a rough forecast for next month sales?'),
 I('Marketing mix, ML-driven analytics','A','Not needed.',1,0,
  'Skip these for entry-level interviews.',
  'Belongs to senior analytics and data science roles.',
  'Marketing mix modelling estimates the effect of each channel on sales.',
  'Have you used machine learning in your analysis?')
]},

{id:'survey',name:'Survey Analytics (your edge)',emoji:'📋',
intro:'Your survey programming experience is a real advantage, especially for market research, CX and consulting firms. It is a small share of general Data Analyst interviews, but a strong talking point in projects and "tell me about yourself".',
order:'NPS/CSAT and Likert first, then base sizes and weighting, then data quality and reshaping survey data, then crosstabs and significance, then open-text coding.',
items:[
 I('NPS, CSAT, CES calculation','M','NPS = %Promoters - %Detractors.',2,5,
  'Calculate NPS from a 0-10 question (promoters 9-10, detractors 0-6), CSAT as satisfied percentage, and know that NPS ranges from -100 to +100.',
  'Customer experience metrics are the most common survey analytics task.',
  '50 promoters, 30 passives, 20 detractors out of 100 -> NPS = 50 - 20 = 30.',
  'How do you calculate NPS?'),
 I('Likert scales, top-2-box, ordinal data','M','Median/top-2-box over mean.',1,5,
  'Say Likert data is ordinal, so use distribution, top-2-box or median, and be careful averaging.',
  'Shows you understand survey data types.',
  'Top-2-box = % answering 4 or 5 on a 5-point scale.',
  'How would you summarise a 5-point satisfaction question?'),
 I('Base sizes, weighted vs unweighted counts, small samples','M','Always show n and be careful with small groups.',1,0,
  'Report the base for each table, flag small bases and know weighted counts can differ from raw counts.',
  'A percentage on a base of 12 can mislead decision makers.',
  '60 percent of 10 respondents is very uncertain; show n=10 and suppress if below the rule.',
  'How do you treat a segment with only 15 respondents?'),
 I('Crosstabs and significance','M','Compare segments.',1,5,
  'Build a crosstab and say a difference between segments needs a significance test (z-test or chi-square) before you call it real.',
  'Standard research deliverable.',
  'Satisfaction by age group with column percentages and significance letters.',
  'Satisfaction is 72 percent for men and 68 percent for women. Is that a real difference?'),
 I('Weighting, sampling bias, non-response','M','Why raw results mislead.',1,7,
  'Explain that weights correct the sample to match population proportions, for example by age and gender.',
  'Weighting is a core survey concept and a good differentiator.',
  'Women are 60 percent of sample but 50 percent of population, so give women a weight of 0.83.',
  'Why would you weight survey results?'),
 I('Data quality: speeders, straight-liners, duplicates','M','You already know this from programming.',2,5,
  'List checks: speeders (completion time too short), straight-liners, duplicate respondents, illogical answers and open-end gibberish.',
  'Bad respondents ruin conclusions, and this is a direct bridge from your current job.',
  'Remove respondents who finished in less than one third of the median time.',
  'How do you clean survey data?'),
 I('Survey data shapes: multi-select, coded values, wide to long','M','Multi-select questions are many columns; labels vs codes; reshaping for analysis.',1,0,
  'Know how to count multi-select answers, map codes to labels, and unpivot question columns for charts.',
  'This is where survey data is different from a clean sales table and where you can show an edge.',
  'Q5_1..Q5_6 are 0/1 columns, so % selected = AVERAGE of each column.',
  'How do you analyse a multiple-choice question that allows several answers?'),
 I('Open-text coding / theme analysis','M','Quantify comments.',1,0,
  'Read a sample, build a code frame of themes, tag responses and count themes. Mention keyword rules as a faster start.',
  'Turns comments into numbers that managers can use.',
  "Themes: Price, Delivery, Support; count mentions of each.",
  'How would you analyse 5000 open-ended comments?'),
 I('Margin of error and confidence levels in surveys','O','Plus or minus range for a percentage at a confidence level.',1,7,
  'Know roughly how n changes the margin and that it applies to random samples only.',
  'Frequently reported in research deliverables.',
  '95 percent confidence and n=400 gives about +/-5 points.',
  'What does a margin of error of 3 percent mean?'),
 I('Tracking studies and wave comparison','O','Compare the same survey across periods and check changes are significant.',1,0,
  'Compare wave to wave with the same question wording and significance testing.',
  'Common in brand and CX research.',
  'NPS Q1 = 28, Q2 = 33: significant at your base sizes?',
  'How would you show a change in satisfaction between two survey waves?'),
 I('SPSS / Q awareness','O','Common in research firms.',1,0,
  'Know they are standard crosstab and statistics tools and say you can do the same in SQL, Excel or Python.',
  'Appears in market research JDs.',
  'SPSS Crosstabs with chi-square.',
  'Have you worked with SPSS or Q?'),
 I('Respondent privacy and consent','O','Survey data often has personal data; anonymise and respect consent.',1,0,
  'Say you remove or mask identifiers and share only aggregates when possible.',
  'Research and finance clients take this seriously.',
  'Replace email with respondent ID before sharing.',
  'How do you keep respondent data confidential?'),
 I('Conjoint, MaxDiff, driver analysis','A','Research roles only.',1,0,
  'Know the names and the purpose (trade-offs, ranking, what drives satisfaction); skip the maths.',
  'Only for specialised research roles.',
  'MaxDiff: pick best and worst feature in each set.',
  'What is conjoint analysis used for?')
]},

{id:'career',name:'Tools & Career',emoji:'🧰',
intro:'This is what recruiters see and judge before and during the process: resume, projects, communication and a few extra tools. It does not count as technical marks, but it decides who gets shortlisted and who gets the offer.',
order:'Portfolio and GitHub first, then resume and LinkedIn, then project walkthrough and behavioural answers, then job-search routine; extra tools and cloud only after your first DA job.',
items:[
 I('Git and GitHub basics','M','Repos with README.',1,1,
  'Create a repo, commit and push, and write a README that explains the question, data, method and findings. Branching and merging can wait.',
  'Hosts your portfolio and shows basic professional habits.',
  'git add . ; git commit -m "Add sales analysis" ; git push',
  'How do you share your project work with others?'),
 I('Portfolio: 3 projects with insights','M','Quality over quantity.',3,5,
  'Have 3 projects with a clear business question, a clean dashboard or notebook, and 3 insights with recommendations.',
  'Freshers have no job history, so projects are your proof.',
  'Project: Olist e-commerce -> delivery delays hurt repeat purchase rate.',
  'Tell me about a project you are proud of.'),
 I('Project walkthrough (2 minutes + deep dive)','M','Problem, data, method, insight, action, result, and what you would do next.',3,9,
  'Rehearse a 2-minute version and be ready to explain any chart, filter or measure in it.',
  'Manager rounds usually start with "walk me through your project".',
  'Structure: why, data, steps, 2 key findings, recommendation, limitation.',
  'Walk me through one project end to end.'),
 I('ATS-friendly 1-page resume','M','Keywords from the JD.',3,8,
  'Use one page, simple format, tools list and bullets with numbers; copy exact keywords from each JD.',
  'Many companies filter resumes by keyword before a human reads them.',
  'Built Power BI dashboard on 100k orders; found 12 percent late deliveries; recommended carrier change.',
  'Why should we shortlist your resume?'),
 I('Translating survey programming work into analyst bullets','M','Show data work you already do: QA, cleaning, logic checks, reporting and deadlines.',2,8,
  'Rewrite each duty as action plus data plus result, such as cleaned and validated survey datasets.',
  'Your 2 years of experience matter more when they are framed as analyst work.',
  'Programmed and QA-checked 40+ surveys; built data-quality checks that removed 8 percent bad responses.',
  'How is your current role relevant to data analysis?'),
 I('LinkedIn headline, About, Featured','M','Show projects.',2,8,
  'Set a headline with target role and tools, a short About, and Featured links to your projects.',
  'Recruiters search LinkedIn for skills.',
  'Survey Programmer transitioning to Data Analyst | SQL | Power BI | Python',
  'What is in your LinkedIn Featured section?'),
 I('Behavioural answers: tell me about yourself, why switch, STAR','M','Prepare short stories using Situation, Task, Action, Result.',3,11,
  'Script and rehearse 60-90 second answers, and prepare 3 STAR stories (error fixed, deadline, disagreement).',
  'Every interview has HR or manager questions and many rejections happen here.',
  'Why switch: "I already clean and validate data every day and want to move into analysis and decisions."',
  'Tell me about a time you found an error in your data.'),
 I('Interview communication: think aloud and clarify','M','Restate the question, ask clarifying questions, explain your plan, and mention edge cases.',2,10,
  'For SQL and cases, say your approach before coding and check your answer with a small example.',
  'Interviewers hire people they can follow, not only those with correct output.',
  'Before writing: "I will join orders to customers, filter 2025, then group by month."',
  'You are stuck on a SQL problem. What do you do in the interview?'),
 I('Tableau Public','O','Many JDs list it.',2,11,
  'Know the basics and have one dashboard published; the ideas transfer from Power BI.',
  'Many JDs list Power BI or Tableau as alternatives.',
  'Publish a dashboard to Tableau Public and add the link to your resume.',
  'Have you used Tableau as well as Power BI?'),
 I('Google Sheets, Looker Studio, BigQuery','O','Alternative stack.',1,0,
  'Know Sheets has QUERY and IMPORTRANGE, Looker Studio is Google free BI and BigQuery is a SQL warehouse; skills transfer.',
  'Startups and marketing teams often use Google tools instead of Microsoft.',
  '=QUERY(A1:D100, "select B, sum(D) group by B")',
  'Can you use Google Sheets or Looker Studio?'),
 I('Job-search routine: applications, referrals, tracker','O','Apply daily, ask for referrals and track follow-ups.',1,8,
  'Aim for a steady number of tailored applications and a tracker with status and dates.',
  'Volume and follow-up matter in the Indian market.',
  'Tracker columns: company, role, date, referral, status, next step.',
  'How are you approaching your job search?'),
 I('Salary research and negotiation','O','Use Glassdoor and AmbitionBox for ranges.',1,12,
  'Know a realistic range for your city and role and give an answer with a range.',
  'HR always asks for expected salary.',
  'I am looking for X to Y based on my skills and market data.',
  'What are your salary expectations?'),
 I('Airflow, dbt, cloud (AWS/Azure/GCP)','A','Only after the first DA job.',1,12,
  'Awareness only; skip learning them before you get your first analyst role.',
  'Used by analytics engineers and larger data teams.',
  'dbt models SQL transformations; Airflow schedules pipelines.',
  'Do you know any cloud data tools?')
]}
];
