/* Generated by tools/build-pages.js. Offline support: pages and scripts are cached;
   when online the network copy is used first, so updates always arrive. */
const CACHE = 'daq-muzyehgb';
const ASSETS = [
 "./",
 "index.html",
 "plan.html",
 "review.html",
 "mock.html",
 "topics.html",
 "interview.html",
 "progress.html",
 "checkin.html",
 "notes.html",
 "search.html",
 "sql-lab.html",
 "projects.html",
 "jobs.html",
 "resources.html",
 "settings.html",
 "qa-sql.html",
 "qa-pbi.html",
 "qa-excel.html",
 "qa-py.html",
 "qa-stats.html",
 "qa-biz.html",
 "qa-survey.html",
 "qa-hr.html",
 "week-1.html",
 "week-2.html",
 "week-3.html",
 "week-4.html",
 "week-5.html",
 "week-6.html",
 "week-7.html",
 "week-8.html",
 "week-9.html",
 "week-10.html",
 "week-11.html",
 "week-12.html",
 "manifest.webmanifest",
 "css/style.css",
 "css/features.css",
 "js/app.js",
 "js/checkin.js",
 "js/core.js",
 "js/data-misc.js",
 "js/data-plan.js",
 "js/data-projects.js",
 "js/data-qa.js",
 "js/data-topics.js",
 "js/guide-w1.js",
 "js/guide-w10.js",
 "js/guide-w11.js",
 "js/guide-w12.js",
 "js/guide-w2.js",
 "js/guide-w3.js",
 "js/guide-w4.js",
 "js/guide-w5.js",
 "js/guide-w6.js",
 "js/guide-w7.js",
 "js/guide-w8.js",
 "js/guide-w9.js",
 "js/guides-init.js",
 "js/mock.js",
 "js/notes.js",
 "js/page-dashboard.js",
 "js/page-interview.js",
 "js/page-jobs.js",
 "js/page-plan.js",
 "js/page-projects.js",
 "js/page-qa.js",
 "js/page-resources.js",
 "js/page-settings.js",
 "js/page-sqllab.js",
 "js/page-topics.js",
 "js/page-week.js",
 "js/progress.js",
 "js/qa-biz-survey-hr.js",
 "js/qa-pbi-excel.js",
 "js/qa-py-stats.js",
 "js/qa-sql.js",
 "js/search.js",
 "js/sr.js",
 "js/timer.js",
 "js/ux.js",
 "icons/apple-touch-icon.png",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/icon-maskable-512.png"
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE && k !== 'daq-cdn').map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin === location.origin) {
    // same site: network first (4 s limit), fall back to the cache when offline
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        const ctl = new AbortController();
        const t = setTimeout(() => ctl.abort(), 4000);
        const res = await fetch(req, { signal: ctl.signal });
        clearTimeout(t);
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      } catch (err) {
        const hit = await cache.match(req, { ignoreSearch: true });
        if (hit) return hit;
        if (req.mode === 'navigate') return (await cache.match('index.html')) || Response.error();
        return Response.error();
      }
    })());
  } else if (url.hostname === 'cdnjs.cloudflare.com') {
    // SQL Lab engine: cache after first use so the lab works offline
    e.respondWith(caches.open('daq-cdn').then(async (c) => {
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res && (res.ok || res.type === 'opaque')) c.put(req, res.clone());
      return res;
    }));
  }
});
